name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/app"
          strip_components: 0

      - name: Execute deployment on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app

            # Ensure Docker is running
            echo "Checking Docker daemon status..."
            if ! pgrep -x "dockerd" > /dev/null; then
              echo "Docker is not running. Starting Docker..."
              sudo systemctl start docker
            else
              echo "Docker is already running."
            fi

            # Make deploy script executable
            chmod +x deploy.sh

            # Create .env file if it doesn't exist
            if [ ! -f .env ]; then
              echo "Creating .env file from example..."
              cp env.example .env
            fi

            # Run deployment
            ./deploy.sh

            # Check if deployment was successful
            if [ $? -eq 0 ]; then
              echo "Deployment completed successfully!"
            else
              echo "Deployment failed!"
              exit 1
            fi

